name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: build image
        run: |
            docker buildx build -t my-app:nginx .
            docker tag my-app:nginx my-app:latest
  push-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-aws-account-id: false
          aws-region: us-east-1
          

      - name: aws credentials OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: false 
          role-to-assume: ${{ secrets.ECR_ROLE_ROLE }}
          aws-region: us-east-1
          run: |
           docker push ${{ secrets.ECR_REPO }}/${{ secrets.ECR_REPO }}:latest
           