name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: build image
        run: |
            docker buildx build -t my-app:nginx .
            docker tag my-app:nginx my-app:latest
             